### ISSUE TITLE
Invalid Barcode Error

### ISSUE THREAD

**Issue by icegit** [MicroPyramid/django-mfa#15]
I have just installed the mfa module and followed the steps. Using Google Authenticator it says that the barcode is not valid. Do you have any idea about this?

**Comment by chaitu210** [comment]
@icegit currently we are creating barcode from user email, you will be facing this issue if the user email is empty. We are about to change this soon, instead of creating from email we will create it with some unique string.

**Comment by icegit** [comment]
Thanks for the quick response. In my case, there is a valid email address, indeed. Since I made a fresh installation, I cannot reproduce the same error now. I will look into this module later on. Is it maybe because I run in the localhost?

**Comment by willingham** [comment]
I'm facing this same issue, even with the email set.

**Comment by nath** [comment]
I put a fix for this in PR #18

**Comment by dmyerscough** [comment]
@nath cool; this fixed the issue. Are there any plans to cut a release upload this fix to pypi

**Comment by chaitu210** [comment]
@dmyerscough we have released v1.0 with the current master code. @willingham thanks for the idea for the fiix, @nath thanks for the fix.

**Comment by ashwin31** [comment]
@dmyerscough we have released new version with this fix.
