### ISSUE TITLE
Support Django 2.0

### ISSUE THREAD

**Issue by ACPK** [MicroPyramid/django-mfa#19]
When I installed this package, it downgraded my version of Django.

**Comment by gregkster** [comment]
My take on Django 2.0 support is here https://github.com/MicroPyramid/django-mfa/pull/30

**Comment by pkondainmar** [comment]
Added support or still in progress ?

**Comment by gregkster** [comment]
It's already done and merged.  This issue should be closed.

**Comment by LyohaProto** [comment]
https://github.com/MicroPyramid/django-mfa/blob/0695ee3238a8f1bcd9c07c4bca46966baefe5dc1/setup.py#L48

It is impossible to use the package with Django 2.0.

**Comment by ashwin31** [comment]
@LyohaProto @gregkster tests were failing, fixing them now.

**Comment by GuganVignesh** [comment]
Still not resolved ??? its still not supporting Django 2.0.0 or later !
