### ISSUE TITLE
How to set the issuer name ?

### ISSUE THREAD

**Issue by GuganVignesh** [MicroPyramid/django-mfa#29]
Guys, to whomsoever who helped get this app on board, I request you to include the issuer name, because once the mfa code is scanned using the google authenticator, the app for which these codes are used is missing so it would be great if we can include the issuer name to avoid confusion.

Screen Shot : 

![img_9561](https://user-images.githubusercontent.com/21262157/45153502-db57d000-b1f1-11e8-89c6-d4c842fb9124.jpg)

please treat this as one of a major issue and fix !

Thanks in advance

**Comment by gregkster** [comment]
I fixed it here https://github.com/gregkster/django-mfa/commit/8b9c4aaeea913a3aff3441843da680506dbce83a#diff-502f38b21ccc1e0cf58cd990904cd694
It is part of this pull request https://github.com/MicroPyramid/django-mfa/pull/31

**Comment by GuganVignesh** [comment]
so how can I get it ?? should I reinstall or upgrade package from pip ??? when is it getting released ?

**Comment by chaitu210** [comment]
@GuganVignesh we are doing  primary testing, once the PR satisfies all the criteria we will be releasing it, you can expect the new release probably by today.

**Comment by GuganVignesh** [comment]
cool thanks its one of the important thought it looks a small fix , thanks . So I just need to upgrade and install I hope ? @chaitu210

**Comment by chaitu210** [comment]
@GuganVignesh yes correct, also you might need to add setting to see the issuer name.

**Comment by chaitu210** [comment]
@GuganVignesh released new update with this fix.
