### ISSUE TITLE
Not compatible with Django 2.0.0 or greater : While installing the package Django is downgraded to  1.11.20

### ISSUE THREAD

**Issue by GuganVignesh** [MicroPyramid/django-mfa#38]
Since I have the latest django project on Django-2.0.7, while installing django-mfa, django is downgraded to  Django-1.11.20 which is not desirable. 

It would be great if mfa supports django 2.0.0 or > !!!

**Comment by gregkster** [comment]
The code supports it.  Something must be wrong with the packaging process or the new version has not made it to the pip repository yet.

**Comment by GuganVignesh** [comment]
@gregkster I guess the recent deployed version or merge had created some issue in the pip repository I guess. Because few days back there was no issue with this the project was running fine with Django 2.0.1 but since yesterday I observed during the pip installation the Django version is been downgraded and django-mfa got installed ....

I guess this should be a killer issue now because my other modules are using the changes from the 2.0 so I cannot even downgrade the projects django version 

It would be of great help if the latest version release of django-mfa is available for pip and pip3 for us to install

**Comment by GuganVignesh** [comment]
@chaitu210 @gregkster @ashwin31

**Comment by GuganVignesh** [comment]
Any updates ? or comments on this issue ? @ashwin31 @gregkster  @chaitu210

**Comment by GuganVignesh** [comment]
<img width="774" alt="Screenshot 2019-03-16 at 9 32 06 PM" src="https://user-images.githubusercontent.com/21262157/54478074-7d591480-4834-11e9-9294-4d71fc807860.png">

**Comment by GuganVignesh** [comment]
Any updates ? @gregkster @chaitu210 @ashwin31

**Comment by chaitu210** [comment]
@GuganVignesh  django_mfa==1.2 fixes the issue.
