### ISSUE TITLE
How could we recover access if we were to lose all of our MFA devices?

### ISSUE THREAD

**Issue by mitchdowney** [MicroPyramid/django-mfa#41]
Last I checked, django-mfa doesn't support backup codes. That's not a dealbreaker for our project as long as there's a way for us to disable MFA and recover access in the event we lose all of our MFA devices. Is there a recovery process we could use if that happens? How would that work? A SQL query perhaps?

Anyway django-mfa is extremely convenient, thank you! :)

**Comment by chaitu210** [comment]
@mitchdowney thanks for using django-mfa. We are working on support for backup codes and support of u2f keys. We will release these 2 updates today. So that you can use this feature. Also we will add feature to disable the MFA from Django Admin panel. I think this solves your problem.

**Comment by mitchdowney** [comment]
@chaitu210 wow that's great news. Thank you!

**Comment by chaitu210** [comment]
@mitchdowney we released new update of Django-mfa for recovery codes, U2F support and added the django admin manage for the mfa enable or disable for user.
