### ISSUE TITLE
Support Django 3

### ISSUE THREAD

**Issue by Datamance** [MicroPyramid/django-mfa#56]
`setup.py` indicates that you can't run this app with a Django version greater than 2.1.5. 

Could you update the code and/or dependency spec to support Django 3? Thanks!

**Comment by ashwin31** [comment]
Sure @Datamance we will target that in a week

**Comment by mwhawkins** [comment]
Having the same problem. Apparently can't install without psycopg2 and a bunch of deprecated packages that won't install alongside Django 3.

**Comment by jensadne** [comment]
Has there been any progress on this? Or would you be interested if I opened a pull request for the changes I've made to make it work on Django 3.2?

**Comment by ausram** [comment]
The second issue with secret_code max_length has been fixed and merged into the repo on the 30th of July, would it be possible to create a release with it? :)

**Comment by ashwin31** [comment]
I will get it done today @ausram
