### ISSUE TITLE
The Error on django3.0

### ISSUE THREAD

**Issue by zsjohny** [MicroPyramid/django-mfa#57]
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'public_key' used in key specification without a key length")

**Comment by icarovirtual** [comment]
Please try the solution I mentioned at #53

**Comment by kamilturek** [comment]
It's solved by #46.

**Comment by kamilturek** [comment]
@abhijeet-1110 Could you please close this issue? It's solved.
