### ISSUE TITLE
Error during template rendering caused by base.html

### ISSUE THREAD

**Issue by ALEX-PETROU** [MicroPyramid/django-mfa#64]
This issue occurs after first setting up the Django-mfa in a project. when going to "/settings/security/" this error comes up. 

I resolved it by changing the "{% load staticfiles %}" to  "{% load static %}" in the base.html template found in the library files under the route seen in the attached photo. 

![base html issue](https://user-images.githubusercontent.com/52289522/111814982-82348100-88b1-11eb-9a43-c0c4048a9bde.PNG)

**Comment by mcoreia** [comment]
Same for me!

**Comment by kamilturek** [comment]
@abhijeet-1110 Could you please close this issue? It's solved.
